/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import javax.swing.table.DefaultTableModel;
import type.Order;

/**
 *
 * @author up859036, up878976, up877962, up912872
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    Utils utils = new Utils();
    Order order = new Order();

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DialogWarning = new javax.swing.JDialog();
        lblTitle = new javax.swing.JLabel();
        lblContent = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        frameComplete = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ftxtOrder = new javax.swing.JTextArea();
        btnComplete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        lblSize = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWidth = new javax.swing.JTextField();
        txtDepth = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        lblWidth = new javax.swing.JLabel();
        lblDepth = new javax.swing.JLabel();
        lblGrade = new javax.swing.JLabel();
        cboxGrade = new javax.swing.JComboBox<>();
        lblColors = new javax.swing.JLabel();
        cboxColors = new javax.swing.JComboBox<>();
        lblReinBot = new javax.swing.JLabel();
        tbtnReinBot = new javax.swing.JToggleButton();
        lblReinCor = new javax.swing.JLabel();
        tbtnReinCor = new javax.swing.JToggleButton();
        txtQuantity = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblPrice = new javax.swing.JLabel();
        lblSealTop = new javax.swing.JLabel();
        tbtnSealTop = new javax.swing.JToggleButton();
        btnCompleteOrder = new javax.swing.JButton();

        lblTitle.setText("Warning");

        lblContent.setText("Message");

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DialogWarningLayout = new javax.swing.GroupLayout(DialogWarning.getContentPane());
        DialogWarning.getContentPane().setLayout(DialogWarningLayout);
        DialogWarningLayout.setHorizontalGroup(
            DialogWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogWarningLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DialogWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblContent)
                    .addComponent(btnOk))
                .addContainerGap(370, Short.MAX_VALUE))
        );
        DialogWarningLayout.setVerticalGroup(
            DialogWarningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DialogWarningLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(lblContent)
                .addGap(18, 18, 18)
                .addComponent(btnOk)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        frameComplete.setPreferredSize(new java.awt.Dimension(500, 300));
        frameComplete.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                frameCompleteWindowOpened(evt);
            }
        });

        jLabel1.setText("Completed Order");

        ftxtOrder.setColumns(20);
        ftxtOrder.setRows(5);
        ftxtOrder.setEnabled(false);
        jScrollPane2.setViewportView(ftxtOrder);

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frameCompleteLayout = new javax.swing.GroupLayout(frameComplete.getContentPane());
        frameComplete.getContentPane().setLayout(frameCompleteLayout);
        frameCompleteLayout.setHorizontalGroup(
            frameCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(frameCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(frameCompleteLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(frameCompleteLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(btnComplete)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        frameCompleteLayout.setVerticalGroup(
            frameCompleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(frameCompleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnComplete)
                .addGap(8, 8, 8))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Height", "Width", "Depth", "Grade", "Colors", "Reinforced Bottom", "Reinforced Corner", "Sealable Top", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Float.class, java.lang.Float.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        lblSize.setText("Size (m)");

        txtHeight.setText("0.0");
        txtHeight.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHeightFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHeightFocusLost(evt);
            }
        });
        txtHeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHeightActionPerformed(evt);
            }
        });

        txtWidth.setText("0.0");
        txtWidth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWidthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtWidthFocusLost(evt);
            }
        });

        txtDepth.setText("0.0");
        txtDepth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDepthFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDepthFocusLost(evt);
            }
        });

        lblHeight.setText("Height");

        lblWidth.setText("Width");

        lblDepth.setText("Depth");

        lblGrade.setText("Grade");

        cboxGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        lblColors.setText("Colors");

        cboxColors.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2" }));

        lblReinBot.setText("Reinforced Bottom");

        tbtnReinBot.setText("No");
        tbtnReinBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnReinBotActionPerformed(evt);
            }
        });

        lblReinCor.setText("Reinforced Corner");

        tbtnReinCor.setText("No");
        tbtnReinCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnReinCorActionPerformed(evt);
            }
        });

        txtQuantity.setText("0");
        txtQuantity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQuantityFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantityFocusLost(evt);
            }
        });
        txtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantityActionPerformed(evt);
            }
        });

        lblQuantity.setText("Quantity");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        lblPrice.setText("Total Price");

        lblSealTop.setText("Sealable Top");

        tbtnSealTop.setText("No");
        tbtnSealTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnSealTopActionPerformed(evt);
            }
        });

        btnCompleteOrder.setText("Complete Order");
        btnCompleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblSealTop, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblQuantity)
                            .addGap(260, 260, 260))
                        .addComponent(lblReinCor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblReinBot, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdd)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSize)
                                    .addComponent(lblGrade)
                                    .addComponent(lblColors))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(cboxColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHeight)
                                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tbtnReinCor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblWidth)
                                            .addComponent(txtWidth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                                            .addComponent(tbtnReinBot, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(tbtnSealTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtQuantity))
                                        .addGap(52, 52, 52)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblDepth)
                                            .addComponent(txtDepth, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCompleteOrder)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRemove)
                                .addGap(18, 18, 18)
                                .addComponent(lblPrice)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemove)
                            .addComponent(lblPrice))
                        .addGap(18, 18, 18)
                        .addComponent(btnCompleteOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(lblWidth)
                            .addComponent(lblDepth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSize)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDepth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGrade)
                            .addComponent(cboxGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblColors)
                            .addComponent(cboxColors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblReinBot)
                            .addComponent(tbtnReinBot))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblReinCor)
                            .addComponent(tbtnReinCor))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSealTop)
                            .addComponent(tbtnSealTop))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuantity))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtnReinBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnReinBotActionPerformed
        utils.toggleYesNo((javax.swing.JToggleButton) evt.getSource());
    }//GEN-LAST:event_tbtnReinBotActionPerformed

    private void tbtnReinCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnReinCorActionPerformed
        utils.toggleYesNo((javax.swing.JToggleButton) evt.getSource());
    }//GEN-LAST:event_tbtnReinCorActionPerformed

    private void txtHeightFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHeightFocusLost
        utils.addPlaceholderText((javax.swing.JTextField) evt.getSource(), "0.0");
        if (utils.checkFloatType((javax.swing.JTextField) evt.getSource())) {
            if (!utils.rangeLimit((javax.swing.JTextField) evt.getSource(), 0.01f, 6f)) {
                // TODO: Dialog box
                utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Height must be in the range of 0.01 to 6");
            };
        } else {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Height must be a float");
        }
    }//GEN-LAST:event_txtHeightFocusLost

    private void txtWidthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWidthFocusLost
        utils.addPlaceholderText((javax.swing.JTextField) evt.getSource(), "0.0");
        if (utils.checkFloatType((javax.swing.JTextField) evt.getSource())) {
            if (!utils.rangeLimit((javax.swing.JTextField) evt.getSource(), 0.01f, 6f)) {
                // TODO: Dialog box
                utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Width must be in the range of 0.01 to 6");
            };
        } else {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Width must be a float");
        }
    }//GEN-LAST:event_txtWidthFocusLost

    private void txtDepthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepthFocusLost
        utils.addPlaceholderText((javax.swing.JTextField) evt.getSource(), "0.0");
        if (utils.checkFloatType((javax.swing.JTextField) evt.getSource())) {
        if (!utils.rangeLimit((javax.swing.JTextField) evt.getSource(), 0.01f, 6f)) {
            // TODO: Dialog box
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Depth must be in the range of 0.01 to 6");
        };
        } else {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Depth must be a float");
        }
    }//GEN-LAST:event_txtDepthFocusLost

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        float height = Float.parseFloat(txtHeight.getText());
        float width = Float.parseFloat(txtWidth.getText());
        float depth = Float.parseFloat(txtDepth.getText());
        int grade = Integer.parseInt(cboxGrade.getSelectedItem().toString());
        int colors = Integer.parseInt(cboxColors.getSelectedItem().toString());
        boolean reinforcedBottom = "Yes".equals(tbtnReinBot.getText());
        boolean reinforcedCorner = "Yes".equals(tbtnReinCor.getText());
        boolean sealabletop = "Yes".equals(tbtnSealTop.getText());
        int quantity = Integer.parseInt(txtQuantity.getText());
        boolean valid = false;
        if (!(depth == 0.0 || width == 0.0 || height == 0.0 || quantity == 0)) {
            valid = order.addOrder(height, width, depth, grade, colors, reinforcedBottom, reinforcedCorner, sealabletop, quantity);
        }
        System.out.println(valid);
        if (valid) {
            Object[] row = {height, width, depth, grade, colors, reinforcedBottom, reinforcedCorner, sealabletop, quantity, String.format("%.2f", order.getPrice(tblOrders.getModel().getRowCount()))};
            DefaultTableModel model = (DefaultTableModel) tblOrders.getModel();
            model.addRow(row);
            lblPrice.setText(String.format("Total Price: £%.2f", order.calculateTotalPrice()));
        } else {
            // TODO: Calculate why its not valid
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Not a valid box");
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void txtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantityActionPerformed
        utils.checkFloatType((javax.swing.JTextField) evt.getSource());
    }//GEN-LAST:event_txtQuantityActionPerformed

    private void tbtnSealTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnSealTopActionPerformed
        utils.toggleYesNo((javax.swing.JToggleButton) evt.getSource());

    }//GEN-LAST:event_tbtnSealTopActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        if (tblOrders.getModel().getRowCount() == 0) {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "You can't remove nothing");
            return;
        }
        int index = tblOrders.getSelectedRow();
        System.out.println(index);
        DefaultTableModel model = (DefaultTableModel) tblOrders.getModel();
        model.removeRow(index);
        order.removeOrder(index);
        lblPrice.setText(String.format("Total Price: £%.2f", order.calculateTotalPrice()));

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtHeightFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHeightFocusGained
        utils.removePlaceholderText((javax.swing.JTextField) evt.getSource(), "0.0");
    }//GEN-LAST:event_txtHeightFocusGained

    private void txtWidthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWidthFocusGained
        utils.removePlaceholderText((javax.swing.JTextField) evt.getSource(), "0.0");
    }//GEN-LAST:event_txtWidthFocusGained

    private void txtDepthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDepthFocusGained
        utils.removePlaceholderText((javax.swing.JTextField) evt.getSource(), "0.0");
    }//GEN-LAST:event_txtDepthFocusGained

    private void txtQuantityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusLost
        utils.addPlaceholderText((javax.swing.JTextField) evt.getSource(), "0");
        if (utils.checkIntType((javax.swing.JTextField) evt.getSource())) {
        if (!utils.rangeLimit((javax.swing.JTextField) evt.getSource(), 0, 10000000)) {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Can't order negative of item");
        };
        } else {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "Quantity must be an Integer");
        }
    }//GEN-LAST:event_txtQuantityFocusLost

    private void txtQuantityFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantityFocusGained
        utils.removePlaceholderText((javax.swing.JTextField) evt.getSource(), "0");
    }//GEN-LAST:event_txtQuantityFocusGained

    private void btnCompleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteOrderActionPerformed
        if (tblOrders.getModel().getRowCount() == 0) {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Warning", "You have ordered nothing");
        } else {
            utils.warningMessage(DialogWarning, lblTitle, lblContent, "Order Complete", "You order has been completed.\nYour total price is " + lblPrice.getText());
            frameComplete.setEnabled(true);
            frameComplete.setVisible(true);
            frameComplete.setSize(new Dimension(500, 500));
        }
    }//GEN-LAST:event_btnCompleteOrderActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        DialogWarning.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void frameCompleteWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_frameCompleteWindowOpened
        ftxtOrder.setText(order.getInvoice());
    }//GEN-LAST:event_frameCompleteWindowOpened

    private void txtHeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHeightActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btnCompleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog DialogWarning;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnCompleteOrder;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cboxColors;
    private javax.swing.JComboBox<String> cboxGrade;
    private javax.swing.JFrame frameComplete;
    private javax.swing.JTextArea ftxtOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblColors;
    private javax.swing.JLabel lblContent;
    private javax.swing.JLabel lblDepth;
    private javax.swing.JLabel lblGrade;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JLabel lblReinBot;
    private javax.swing.JLabel lblReinCor;
    private javax.swing.JLabel lblSealTop;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWidth;
    private javax.swing.JTable tblOrders;
    private javax.swing.JToggleButton tbtnReinBot;
    private javax.swing.JToggleButton tbtnReinCor;
    private javax.swing.JToggleButton tbtnSealTop;
    private javax.swing.JTextField txtDepth;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtWidth;
    // End of variables declaration//GEN-END:variables
}
